name: 'Create Check Report'
description: 'Create a check report by using check-run'
author: 'maxisam'
branding:
  icon: file-text
  color: green
inputs:
  authToken:
    description: 'Use your own token if you need to trigger other workflows'
    default: ${{ github.token }}
    required: false
  owner:
    description: 'Repostory owner, defaults to context github.repository_owner if omited'
    default: ${{ github.repository_owner }}
    required: false
  repository:
    description: 'Repository, default to context github.repository if omited'
    default: ${{ github.repository }}
    required: false
  checkName:
    description: 'Name of the check'
    default: Check Report
    required: false
  sha:
    description: 'Github SHA'
    default: ${{ github.sha }}
    required: false
  status:
    description: 'Check Status'
    default: completed
    required: false
  conclusion:
    description: 'Conclusion'
    default: success
    required: false
  summary:
    description: 'Summary'
    default: 'Summary'
    required: false
  content:
    description: 'Content, you can use multiline with markdown syntax'
    default: ''
    required: false
  detailsUrl:
    description: 'Details url'
    default: ''
    required: false
  imageUrl:
    description: The full URL of the image.
    default: 'https://avatars.githubusercontent.com/in/15368?s=40&v=4'
    required: false
 
runs:
  using: 'node16'
  main: 'dist/index.js'